// istanbul ignore file
export const appName = 'Penumbra Blockchain Explorer'
export const fastOutSlowIn = [0.4, 0, 0.2, 1]

export const ibc = [
    {
        addressPrefix: 'cosmos',
        chainId: 'cosmoshub-4',
        channelId: 'channel-0',
        clientStatus: 'active',
        counterpartyChannelId: 'channel-940',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: 'Cosmos Hub',
        txsExpired: 1,
        txsPending: 3,
        txsShielded: 740,
        txsUnshielded: 403,
        volumeShielded: 12687.9,
        volumeUnshielded: 6852.2,
    },
    {
        addressPrefix: 'noble',
        chainId: 'noble-1',
        channelId: 'channel-2',
        clientStatus: 'active',
        counterpartyChannelId: 'channel-89',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/stake.svg',
        name: 'Noble',
        txsExpired: 0,
        txsPending: 10,
        txsShielded: 86,
        txsUnshielded: 317,
        volumeShielded: 9712.56,
        volumeUnshielded: 9471.4,
    },
    {
        addressPrefix: 'celestia',
        chainId: 'celestia',
        channelId: 'channel-3',
        clientStatus: 'frozen',
        counterpartyChannelId: 'channel-35',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/celestia/images/celestia.svg',
        name: 'Celestia',
        txsExpired: 1,
        txsPending: 0,
        txsShielded: 362,
        txsUnshielded: 794,
        volumeShielded: 5738.83,
        volumeUnshielded: 7555.3,
    },
    {
        addressPrefix: 'osmo',
        chainId: 'osmosis-1',
        channelId: 'channel-4',
        clientStatus: 'expired',
        counterpartyChannelId: 'channel-79703',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/osmo.svg',
        name: 'Osmosis',
        txsExpired: 3,
        txsPending: 14,
        txsShielded: 547,
        txsUnshielded: 28,
        volumeShielded: 3980.26,
        volumeUnshielded: 5246.72,
    },
    {
        addressPrefix: 'stride',
        chainId: 'stride-1',
        channelId: 'channel-8',
        clientStatus: 'unknown',
        counterpartyChannelId: 'channel-307',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/strd.svg',
        name: 'Stride',
        txsExpired: 0,
        txsPending: 423,
        txsShielded: 994,
        txsUnshielded: 661,
        volumeShielded: 2437.28,
        volumeUnshielded: 8677.68,
    },
    {
        addressPrefix: 'neutron',
        chainId: 'neutron-1',
        channelId: 'channel-9',
        clientStatus: 'active',
        counterpartyChannelId: 'channel-6560',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/neutron/images/neutron.svg',
        name: 'Neutron',
        txsExpired: 0,
        txsPending: 20,
        txsShielded: 830,
        txsUnshielded: 194,
        volumeShielded: 1858.54,
        volumeUnshielded: 9891.56,
    },
    {
        addressPrefix: 'axelar',
        chainId: 'axelar-dojo-1',
        channelId: 'channel-7',
        clientStatus: 'frozen',
        counterpartyChannelId: 'channel-171',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/axelar/images/axl.svg',
        name: 'Axelar',
        txsExpired: 0,
        txsPending: 0,
        txsShielded: 848,
        txsUnshielded: 689,
        volumeShielded: 4052.84,
        volumeUnshielded: 8849.39,
    },
]
