// istanbul ignore file
export default [
    {
        chainId: 'cosmoshub-4',
        id: '07-tendermint-0',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: 'Cosmos Hub',
        slug: 'cosmoshub',
    },
    {
        chainId: 'dxdy-mainnet-1',
        id: '07-tendermint-1',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/dydx/images/dydx.svg',
        name: 'dYdX Protocol',
        slug: 'dydx',
    },
    {
        chainId: 'noble-1',
        id: '07-tendermint-2',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/stake.svg',
        name: 'Noble',
        slug: 'noble',
    },
    {
        chainId: 'celestia',
        id: '07-tendermint-3',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/celestia/images/celestia.svg',
        name: 'Celestia',
        slug: 'celestia',
    },
    {
        chainId: 'osmosis-1',
        id: '07-tendermint-4',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/osmo.svg',
        name: 'Osmosis',
        slug: 'osmosis',
    },
    {
        chainId: 'neutron-1',
        id: '07-tendermint-5',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/neutron/images/neutron.svg',
        name: 'Neutron',
        slug: 'neutron',
    },
    {
        chainId: 'axelar-dojo-1',
        id: '07-tendermint-7',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/axelar/images/axl.svg',
        name: 'Axelar',
        slug: 'axelar',
    },
    {
        chainId: 'stride-1',
        id: '07-tendermint-8',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/strd.svg',
        name: 'Stride',
        slug: 'stride',
    },
    {
        chainId: 'injective-1',
        id: '07-tendermint-20',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/inj.svg',
        name: 'Injective Finance',
        slug: 'injective',
    },
]
