// istanbul ignore file
export default [
    {
        chainId: 'cosmoshub-4',
        clientId: '07-tendermint-0',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: 'Cosmos Hub',
    },
    {
        chainId: 'dxdy-mainnet-1',
        clientId: '07-tendermint-1',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/dydx/images/dydx.svg',
        name: 'dYdX Protocol',
    },
    {
        chainId: 'noble-1',
        clientId: '07-tendermint-2',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/stake.svg',
        name: 'Noble',
    },
    {
        chainId: 'celestia',
        clientId: '07-tendermint-3',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/celestia/images/celestia.svg',
        name: 'Celestia',
    },
    {
        chainId: 'osmosis-1',
        clientId: '07-tendermint-4',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/osmo.svg',
        name: 'Osmosis',
    },
    {
        chainId: 'neutron-1',
        clientId: '07-tendermint-5',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/neutron/images/neutron.svg',
        name: 'Neutron',
    },
    {
        chainId: '07-tendermint-6',
        clientId: '07-tendermint-6',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-6',
    },
    {
        chainId: 'axelar-dojo-1',
        clientId: '07-tendermint-7',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/axelar/images/axl.svg',
        name: 'Axelar',
    },
    {
        chainId: 'stride-1',
        clientId: '07-tendermint-8',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/strd.svg',
        name: 'Stride',
    },
    {
        chainId: '07-tendermint-9',
        clientId: '07-tendermint-9',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-9',
    },
    {
        chainId: '07-tendermint-10',
        clientId: '07-tendermint-10',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-10',
    },
    {
        chainId: '07-tendermint-11',
        clientId: '07-tendermint-11',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-11',
    },
    {
        chainId: '07-tendermint-12',
        clientId: '07-tendermint-12',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-12',
    },
    {
        chainId: '07-tendermint-13',
        clientId: '07-tendermint-13',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-13',
    },
    {
        chainId: '07-tendermint-14',
        clientId: '07-tendermint-14',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-14',
    },
    {
        chainId: '07-tendermint-15',
        clientId: '07-tendermint-15',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-15',
    },
    {
        chainId: '07-tendermint-16',
        clientId: '07-tendermint-16',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-16',
    },
    {
        chainId: '07-tendermint-17',
        clientId: '07-tendermint-17',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-17',
    },
    {
        chainId: '07-tendermint-18',
        clientId: '07-tendermint-18',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-18',
    },
    {
        chainId: '07-tendermint-19',
        clientId: '07-tendermint-19',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-19',
    },
    {
        chainId: '07-tendermint-20',
        clientId: '07-tendermint-20',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-20',
    },
    {
        chainId: '07-tendermint-21',
        clientId: '07-tendermint-21',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-21',
    },
    {
        chainId: '07-tendermint-22',
        clientId: '07-tendermint-22',
        image: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.svg',
        name: '07-tendermint-22',
    },
]
