steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gcloud
    # Cloud Build environment variables
    env:
      - _ENV_NAME=${_ENV_NAME}
    args:
      # Deploy from source
      - run
      - deploy
      - penumbra-explorer-${_ENV_NAME}
      - --source
      - .
      - --region
      - ${_REGION}
      - --allow-unauthenticated
      # Settings recommended by AI for this Next.js setup
      - --memory=2Gi
      - --cpu=2
      - --min-instances=1
      - --concurrency=20
      - --platform=managed
      # Cloud Run environment variables
      - --set-env-vars
      - _ENV_NAME=${_ENV_NAME}
