schema: src/lib/graphql/schema.graphql
extensions:
  endpoints:
    dev:
      headers:
        user-agent: JS GraphQL
      introspect: false
      url: https://pe-backend-564694434950.europe-west6.run.app/graphql
