schema: src/lib/graphql/schema.graphql
extensions:
  endpoints:
    dev:
      headers:
        user-agent: JS GraphQL
      introspect: false
      url: https://dev.api.explorer.penumbra.pklabs.me/graphql
