name: Deploy to development

on:
  push:
    branches:
      - main

jobs:
  trigger_gcp_workflow:
    uses: ./.github/workflows/gcp.yaml
    with:
      env_name: prod
      env_name_label: development
      gcp_region: europe-west4
    secrets: inherit
