name: Deploy to production

on:
  workflow_dispatch:

jobs:
  trigger_gcp_workflow:
    uses: ./.github/workflows/gcp.yaml
    with:
      env_name: prod
      env_name_label: production
      gcp_region: us-east4
    secrets: inherit
