name: Deploy to production

on:
  workflow_dispatch:

jobs:
  trigger_gcp_workflow:
    uses: ./.github/workflows/gcp.yaml
    with:
      env_name_long: production
      env_name_short: prod
      gcp_region: us-east4
    secrets: inherit
