name: Deploy to staging

on:
  workflow_dispatch:

jobs:
  trigger_gcp_workflow:
    uses: ./.github/workflows/gcp.yaml
    with:
      env_name: staging
      env_name_label: staging
      gcp_region: us-east4
    secrets: inherit
