name: Deploy to staging

on:
  push:
    branches:
      - staging

# TOOD: Copy .env.staging to .env
jobs:
  trigger_gcp_workflow:
    uses: ./.github/workflows/gcp.yaml
    with:
      env_name: staging
      env_name_label: staging
      gcp_region: us-east4
    secrets: inherit
