name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  env_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy .env.staging to .env
        run: cp .env.staging .env

      - name: Verify .env creation and content # DEBUGGING STEP
        run: |
          echo "Checking for .env file..."
          if [ -f ".env" ]; then
            echo ".env file FOUND."
            echo "Contents of .env:"
            cat .env
          else
            echo ".env file NOT FOUND."
            echo "Checking if .env.staging exists (for troubleshooting):"
            if [ -f ".env.staging" ]; then
              echo ".env.staging FOUND."
            else
              echo ".env.staging also NOT FOUND at root. Please check its actual path in your repository."
            fi
            exit 1 # Force the job to fail here if .env wasn't created
          fi

      - name: Upload .env artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env
          retention-days: 1

  trigger_gcp_workflow:
    needs: env_setup
    uses: ./.github/workflows/gcp.yaml
    with:
      env_name: staging
      env_name_label: staging
      gcp_region: us-east4
    secrets: inherit
