name: Test workflow

on:
  workflow_call:
    inputs:
      foo:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print stuff
        run: |
          echo "foo is: ${{ inputs.bar }}"
          echo "GITHUB_TOKEN is: ${{ secrets.GITHUB_TOKEN }}"
